package commands

import "fmt"

const About = "about"

func ShowAbout() {
	fmt.Println(`
    ██████  ██     ██  ██████  
   ██    ██ ██     ██ ██    ██ 
   ██    ██ ██  █  ██ ██    ██
   ██    ██ ██ ███ ██ ██    ██ 
    ██████   ███ ███   ██████  

	                 whats this?              
   `)

	fmt.Println("owo was born out of frustration at using the confluence web wiki. It is very hard to quickly access the information I want, and editing the info with new info is a huge pain. For instance, I want to ensure that the health endpoint of one of my services is responding correctly, but I dont remember the port. Should I open the repo and look it up? What about the command to restart the service as managed by daemon tools? Maybe a quick function to check all listening ports on this host? I normally have tons of terminals open so this seemed like a good compromise. Similarly, I wanted some exercise in writing a command line interface handling all the operations myself. As a result, owo has no external dependencies except go and git")
	fmt.Println()
	fmt.Println("owo is a command line executable that allows easy access of small amounts of documentation organized by a filestructure in a git repository. it allows for easy editing of this data to a source of truth hosted in a github repo. owo is handy for people working often on command lines who need access to handy commands and/or documentation. Additional works on github actions and integrations serve to expand functionality and serve as access points for non developers.")
	fmt.Println()
	fmt.Println("owo helps you organize and update your data by allowing for easy updates of information facilitated through git pull requests auto generated by owo")

}
