name: owoPR
on:
  push:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: "owo Automatic Document Update PR"
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
